.PHONY: clean All

All:
	@echo "----------Building project:[ SimplePointer - Debug ]----------"
	@cd "SimplePointer" && "$(MAKE)" -f  "SimplePointer.mk"
clean:
	@echo "----------Cleaning project:[ SimplePointer - Debug ]----------"
	@cd "SimplePointer" && "$(MAKE)" -f  "SimplePointer.mk" clean
