.PHONY: clean All

All:
	@echo "----------Building project:[ MultiDimensinal_array - Debug ]----------"
	@cd "MultiDimensinal_array" && "$(MAKE)" -f  "MultiDimensinal_array.mk"
clean:
	@echo "----------Cleaning project:[ MultiDimensinal_array - Debug ]----------"
	@cd "MultiDimensinal_array" && "$(MAKE)" -f  "MultiDimensinal_array.mk" clean
