.PHONY: clean All

All:
	@echo "----------Building project:[ string - Debug ]----------"
	@cd "string" && "$(MAKE)" -f  "string.mk"
clean:
	@echo "----------Cleaning project:[ string - Debug ]----------"
	@cd "string" && "$(MAKE)" -f  "string.mk" clean
