.PHONY: clean All

All:
	@echo "----------Building project:[ Question-2 - Debug ]----------"
	@cd "Question-2" && "$(MAKE)" -f  "Question-2.mk"
clean:
	@echo "----------Cleaning project:[ Question-2 - Debug ]----------"
	@cd "Question-2" && "$(MAKE)" -f  "Question-2.mk" clean
