.PHONY: clean All

All:
	@echo "----------Building project:[ ShallowCopy - Debug ]----------"
	@cd "ShallowDeepCopy" && "$(MAKE)" -f  "ShallowCopy.mk"
clean:
	@echo "----------Cleaning project:[ ShallowCopy - Debug ]----------"
	@cd "ShallowDeepCopy" && "$(MAKE)" -f  "ShallowCopy.mk" clean
