.PHONY: clean All

All:
	@echo "----------Building project:[ implementingMemberMethod - Debug ]----------"
	@cd "implementingMemberMethod" && "$(MAKE)" -f  "implementingMemberMethod.mk"
clean:
	@echo "----------Cleaning project:[ implementingMemberMethod - Debug ]----------"
	@cd "implementingMemberMethod" && "$(MAKE)" -f  "implementingMemberMethod.mk" clean
